
###
POST  http://localhost:7200/group-staff/ HTTP/1.1
content-type: application/json

{
    "idStaff": 7,
    "idGroup":5
}

###
GET  http://localhost:7200/group-staff/ HTTP/1.1

###
GET  http://localhost:7200/group-staff/2 HTTP/1.1

###
PATCH  http://localhost:7200/group-staff/2 HTTP/1.1
content-type: application/json

{
    "password": "tyuvhjbu"
    
}

###
DELETE  http://localhost:7200/group-staff/4 HTTP/1.1
