###
POST  http://localhost:7200/rule/ HTTP/1.1
content-type: application/json

{
    "description":"cadastrar"
}

###
GET  http://localhost:7200/rule/ HTTP/1.1

###
GET  http://localhost:7200/rule/2 HTTP/1.1

###
PATCH  http://localhost:7200/rule/2 HTTP/1.1
content-type: application/json

{
    "password": "tyuvhjbu"
    
}

###
DELETE  http://localhost:7200/rule/2 HTTP/1.1
