
###
POST  http://localhost:7200/user-site/ HTTP/1.1
content-type: application/json

{
    "login": " fabio",
    "password": "123456",
    "name": "fabio",
    "cpf": 12345678910

    
}

###
GET  http://localhost:7200/user-site/ HTTP/1.1

###
GET  http://localhost:7200/user-site/6 HTTP/1.1

###
PATCH  http://localhost:7200/user-site/6 HTTP/1.1
content-type: application/json

{
    "login": "bwillians.fla@gmail.com"
    
}

###
DELETE  http://localhost:7200/user-site/4 HTTP/1.1

###
POST  http://localhost:7200/user-site/signin HTTP/1.1
content-type: application/json

{
    "login": "bwillians.fla@gmail.com",
    "password": "324307"
}


###
POST  http://localhost:7200/user-site/get-code HTTP/1.1
content-type: application/json

{
    "login": "bwillians.fla@gmail.com"
}