name: publish
on:
  push:
    branches: [ "main" ]
    paths:
      - 'deploy.txt'

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.OVERRIDE_GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: |
           docker build -f Dockerfile . --tag ghcr.io/brenowillians/service-user-producao:1.$GITHUB_RUN_NUMBER
           docker tag ghcr.io/brenowillians/service-user-producao:1.$GITHUB_RUN_NUMBER ghcr.io/brenowillians/service-user-producao:latest
           docker push ghcr.io/brenowillians/service-user-producao:1.$GITHUB_RUN_NUMBER
           docker push ghcr.io/brenowillians/service-user-producao:latest